# StatScholar - TI-84 Python Statistics Tutor
# Author: Gregory King
# Date: 2026-09-20
# Copyright (c) 2026 Gregory King
# SPDX-License-Identifier: LicenseRef-StatScholar-Free-Use-No-Sale-1.0
#
# License terms: see LICENSE or STAT1.py.


# Definition text loads only while browsing a selected bank.

DEFINITIONS = [('population', 'ENTIRE GROUP THE STUDY WANTS TO DESCRIBE.'), ('sample', 'SUBSET OF POPULATION ACTUALLY OBSERVED.'), ('parameter', 'NUMBER DESCRIBING A POPULATION.'), ('statistic', 'NUMBER DESCRIBING A SAMPLE.'), ('qualitative', 'CATEGORICAL DATA; LABELS OR GROUPS.'), ('quantitative', 'NUMERICAL COUNTS OR MEASUREMENTS.'), ('discrete', 'COUNTABLE SEPARATE NUMERICAL VALUES.'), ('continuous', 'MEASURED VALUES THAT CAN VARY THROUGH AN INTERVAL.'), ('frequency', 'NUMBER OF TIMES A VALUE OR CATEGORY OCCURS.'), ('relative frequency', 'FREQUENCY DIVIDED BY TOTAL n.'), ('cumulative frequency', 'RUNNING TOTAL OF FREQUENCIES.'), ('mean', 'SUM OF VALUES DIVIDED BY n.'), ('median', 'MIDDLE ORDERED VALUE; 50TH PERCENTILE.'), ('mode', 'MOST FREQUENT VALUE.'), ('range', 'MAXIMUM MINUS MINIMUM.'), ('q1', 'FIRST QUARTILE; ABOUT LOWEST 25%.'), ('q3', 'THIRD QUARTILE; ABOUT 75% AT OR BELOW.'), ('iqr', 'Q3-Q1; SPREAD OF MIDDLE 50%.'), ('outlier', 'VALUE UNUSUALLY FAR FROM OTHERS.'), ('right skew', 'LONG TAIL TO RIGHT.'), ('left skew', 'LONG TAIL TO LEFT.'), ('sample space', 'SET OF ALL POSSIBLE OUTCOMES.'), ('event', 'SET OF OUTCOMES FROM SAMPLE SPACE.'), ('complement', 'ALL OUTCOMES NOT IN EVENT; 1-P(E).'), ('union', 'A OR B.'), ('intersection', 'A AND B.'), ('mutually exclusive', 'EVENTS CANNOT OCCUR TOGETHER.'), ('independent', 'ONE EVENT DOES NOT CHANGE PROBABILITY OF OTHER.'), ('conditional probability', 'PROBABILITY OF A GIVEN B.'), ('random variable', 'NUMERIC VALUE ASSIGNED TO RANDOM OUTCOME.'), ('expected value', 'LONG-RUN MEAN; SUM[x*P(x)].'), ('binomial distribution', 'FIXED n, TWO OUTCOMES, SAME p, INDEPENDENT.'), ('combination', 'SELECTION WHERE ORDER DOES NOT MATTER; nCr.'), ('permutation', 'ARRANGEMENT WHERE ORDER MATTERS; nPr.'), ('z score', 'NUMBER OF SDs A VALUE IS FROM MEAN.')]

SAMPLING_DEFINITIONS = [
    ('simple random sample', 'EVERY POSSIBLE SUBGROUP OF SIZE n HAS THE SAME CHANCE OF SELECTION. NUMBER EVERYONE, THEN HAVE A COMPUTER RANDOMLY PICK n DISTINCT NUMBERS. EQUAL INDIVIDUAL CHANCES ALONE DO NOT GUARANTEE A SIMPLE RANDOM SAMPLE.'),
    ('random sample', 'EVERY INDIVIDUAL IN THE POPULATION HAS AN EQUAL CHANCE OF BEING IN THE SAMPLE. FOR A SIMPLE RANDOM SAMPLE, EVERY POSSIBLE SUBGROUP OF SIZE n MUST ALSO BE EQUALLY LIKELY.'),
    ('systematic sample', 'CHOOSE A RANDOM START, THEN SELECT EVERY kth MEMBER OF THE POPULATION LIST. EXAMPLE: RANDOMLY START AT 4, THEN TAKE 4, 14, 24, ETC. REPEATING PATTERNS IN THE LIST CAN BIAS THE SAMPLE.'),
    ('convenience sample', 'SELECT PEOPLE WHO ARE EASIEST TO REACH. EXAMPLE: ASK NEARBY FRIENDS. THE SAMPLE MAY NOT REPRESENT THE POPULATION.'),
    ('stratified sample', 'DIVIDE THE POPULATION INTO STRATA: GROUPS ALIKE WITHIN EACH GROUP BUT DIFFERENT BETWEEN GROUPS. RANDOMLY SAMPLE FROM EVERY GROUP. IN PROPORTIONATE STRATIFIED SAMPLING, USE EACH GROUP IN THE SAME PROPORTION AS IN THE POPULATION. EXAMPLE: 60% FRESHMEN IN THE POPULATION, SO 60% OF THE SAMPLE ARE FRESHMEN.'),
    ('cluster sample', 'DIVIDE THE POPULATION INTO GROUPS CALLED CLUSTERS. RANDOMLY SELECT SOME GROUPS, THEN SURVEY EVERYONE IN THE SELECTED GROUPS. EXAMPLE: SELECT SOME CLASSROOMS AND SURVEY ALL THEIR STUDENTS. SAMPLING ONLY SOME PEOPLE WITHIN SELECTED CLUSTERS IS MULTISTAGE SAMPLING.'),
    ('bias', 'A METHOD SYSTEMATICALLY FAVORS SOME RESULTS. A BAD SAMPLING FRAME CAN LEAVE PEOPLE OUT OR OVERREPRESENT OTHERS, SO THE SAMPLE DOES NOT REPRESENT THE POPULATION CHARACTERISTICS. BIASED QUESTIONS AND NONRESPONSE CAN ALSO CAUSE BIAS.')]

MEASUREMENT_DEFINITIONS = [
    ('nominal', 'CATEGORIES WITH NO NATURAL ORDER. EXAMPLES: BLOOD TYPE OR EYE COLOR. NUMBER LABELS DO NOT MAKE THE DATA QUANTITATIVE.'),
    ('ordinal', 'ORDERED CATEGORIES, BUT DIFFERENCES BETWEEN RANKS ARE NOT MEANINGFUL MEASURED GAPS. EXAMPLE: POOR, FAIR, GOOD, EXCELLENT.'),
    ('interval', 'ORDERED NUMERICAL VALUES WITH MEANINGFUL EQUAL DIFFERENCES, BUT NO TRUE ZERO. EXAMPLE: CELSIUS TEMPERATURE. 20 DEGREES C IS NOT TWICE AS HOT AS 10 DEGREES C.'),
    ('ratio', 'NUMERICAL VALUES WITH MEANINGFUL EQUAL DIFFERENCES AND A TRUE ZERO THAT MEANS NONE OF THE QUANTITY. RATIOS ARE MEANINGFUL. EXAMPLES: WEIGHT, HEIGHT, ELAPSED TIME. 20 MINUTES IS TWICE 10 MINUTES.')]

STUDY_DEFINITIONS = [
    ('sampling error', 'CHANCE DIFFERENCE BETWEEN A SAMPLE STATISTIC AND THE POPULATION PARAMETER BECAUSE ONLY A SAMPLE WAS OBSERVED. IT CAN OCCUR EVEN WITH A WELL-DESIGNED RANDOM SAMPLE.'),
    ('non-sampling error', 'ERROR FROM CAUSES OTHER THAN RANDOM SAMPLE VARIATION: BAD MEASUREMENTS, DATA ENTRY MISTAKES, UNDERCOVERAGE, NONRESPONSE, OR MISLEADING QUESTIONS. IT CAN OCCUR IN A SAMPLE OR A CENSUS.'),
    ('statistically significant', 'THE OBSERVED RESULT WOULD BE SUFFICIENTLY UNLIKELY UNDER THE NULL HYPOTHESIS. A TEST DECLARES SIGNIFICANCE WHEN ITS p-VALUE IS AT OR BELOW THE CHOSEN SIGNIFICANCE LEVEL alpha. THIS DOES NOT SHOW THAT THE EFFECT IS LARGE OR IMPORTANT.'),
    ('practically significant', 'THE EFFECT IS LARGE OR IMPORTANT ENOUGH TO MATTER IN REAL LIFE. CONSIDER ITS SIZE, COSTS, AND CONTEXT. A TINY EFFECT CAN BE STATISTICALLY SIGNIFICANT IN A VERY LARGE SAMPLE WITHOUT BEING PRACTICALLY IMPORTANT.'),
    ('outlier', 'A VALUE UNUSUALLY FAR FROM THE OTHER VALUES. COMMON BOXPLOT RULE: BELOW Q1-1.5*IQR OR ABOVE Q3+1.5*IQR, WHERE IQR=Q3-Q1. AN OUTLIER MAY BE REAL OR AN ERROR; IT IS NOT AUTOMATICALLY A MISTAKE.')]

BIAS_DEFINITIONS = [
    ('voluntary response', 'PEOPLE CHOOSE TO JOIN THE SAMPLE, SUCH AS CALLING A RADIO SHOW. STRONG OPINIONS MAY BE OVERREPRESENTED. MORE RESPONSES DO NOT REMOVE THIS BIAS.'),
    ('undercoverage', 'THE SAMPLING FRAME LEAVES OUT PART OF THE TARGET POPULATION. RANDOMLY SAMPLING COLLEGE MEMBERS DOES NOT REPRESENT ALL US ADULTS.'),
    ('nonresponse bias', 'SELECTED PEOPLE DO NOT RESPOND, AND RESPONDENTS DIFFER SYSTEMATICALLY FROM NONRESPONDENTS. LOW RESPONSE ALONE DOES NOT MEASURE THE BIAS.'),
    ('quota sampling', 'FILL SPECIFIED COUNTS FROM POPULATION SUBGROUPS. RANDOM SELECTION WITHIN GROUPS IS NOT REQUIRED. STRATIFIED RANDOM SAMPLING DOES REQUIRE IT.'),
    ('cumulative relative frequency', 'RUNNING COUNT DIVIDED BY TOTAL COUNT. ENDS AT 1; CUMULATIVE FREQUENCY IS A COUNT AND ENDS AT n. USE UNROUNDED COUNTS BEFORE ROUNDING.')]

DEFINITIONS.append(('law of large numbers', 'AS INDEPENDENT TRIALS WITH THE SAME p INCREASE, RELATIVE FREQUENCY TENDS TOWARD TRUE PROBABILITY. SEE RELATIVE FREQUENCY AND EMPIRICAL PROBABILITY.'))

DEFINITIONS.extend([
    ('empirical rule','FOR APPROXIMATELY NORMAL DATA: ABOUT 68%, 95%, 99.7% WITHIN 1, 2, 3 SD. OUTSIDE IS THE COMPLEMENT; SYMMETRIC TAILS SPLIT IT EQUALLY.'),
    ('range rule of thumb','MIN USUAL = MEAN - 2 SD; MAX USUAL = MEAN + 2 SD. CHECK THE QUESTION FOR STRICT OR INCLUSIVE BOUNDARIES. THESE ARE NOT IQR FENCES.'),
    ('multistage sampling','SELECT GROUPS, THEN SAMPLE MEMBERS WITHIN THE SELECTED GROUPS. DISTINGUISH FROM SURVEYING EVERYONE IN EACH CHOSEN CLUSTER.')])


def get_definitions(name,index=None):
    entries=globals()[name]
    return entries if index is None else entries[index]
