# StatScholar - TI-84 Python Statistics Tutor
# Author: Gregory King
# Date: 2026-09-20
# Copyright (c) 2026 Gregory King
# SPDX-License-Identifier: LicenseRef-StatScholar-Free-Use-No-Sale-1.0
#
# License terms: see LICENSE or STAT1.py.

# STGNEW - expansion guide text, loaded on request.
import STCORE

def get_guide(gid,field=None):
    if gid == 'S13':
        return STCORE.unpack_guide('Raw Data Summary\nLIST OF NUMBERS; MEAN MEDIAN SD\nn VALUES; SAMPLE SD USES n-1\nORDER DATA; MEDIANS OF HALVES; OMIT ODD CENTER\n1-VAR STATS L1\n1,2,3,4: MEAN=2.5; Q1=1.5; Q3=3.5\nDO NOT USE POPULATION SD FOR SAMPLE\nS14 S15 S16\nS13', field)
    if gid == 'S14':
        return STCORE.unpack_guide('Sample Variance\nVARIANCE s^2\nSUM SQUARED DISTANCES / (n-1)\nSUBTRACT MEAN; SQUARE; SUM; DIVIDE n-1\nSQUARE Sx FROM 1-VAR STATS\n1,2,3: s^2=1\nVARIANCE HAS SQUARED UNITS\nS13 S09\nS14', field)
    if gid == 'S15':
        return STCORE.unpack_guide('Midrange\nAVERAGE OF MIN AND MAX\n(MIN+MAX)/2\nADD EXTREMES; DIVIDE BY TWO\n1-VAR STATS minX,maxX\n2,4,10: MIDRANGE=6\nNOT THE MEDIAN OR MEAN\nS13\nS15', field)
    if gid == 'S16':
        return STCORE.unpack_guide('Compare Two Data Sets\nCOMPARE GROUPS OR LISTS\nMEAN MEDIAN SD VAR RANGE IQR\nCOMPARE CENTERS AND SPREAD SEPARATELY\n1-VAR STATS FOR EACH LIST\n1,2,3 VS 2,4,6: MEANS 2,4; SDs 1,2\nUSE MORE THAN ONE MEASURE\nG04 G09\nS16', field)
    if gid == 'G04':
        return STCORE.unpack_guide('Boxplot Builder\nDRAW BOX AND WHISKERS\nFIVE NUMBER SUMMARY; IQR; FENCES\nBOX Q1 TO Q3; MEDIAN LINE; NON-OUTLIER WHISKERS\nSTAT PLOT MODIFIED BOXPLOT\n1,2,3,4,100: UPPER FENCE=127; NO OUTLIER\nFIVE NUMBERS MAY NOT IDENTIFY MODIFIED WHISKERS\nS13 S16\nG04', field)
    if gid == 'G05':
        return STCORE.unpack_guide('Dotplot Builder\nDRAW DOTS FOR DATA\nVALUE AND COUNT\nSTACK REPEATS; KEEP NUMERIC AXIS SPACING\nUSE COUNTS TO DRAW ON PAPER\n20,22,22: COUNTS 1,0,2 AT 20,21,22\nDO NOT OMIT SPACING FOR MISSING VALUES\nS13 G06\nG05', field)
    if gid == 'G06':
        return STCORE.unpack_guide('Histogram Builder\nHISTOGRAM BARS OR CLASSES\nRAW VALUES, FREQUENCIES, OR P(X)\nCHOOSE CLASSES; COUNT EACH OBSERVATION ONCE\nSTAT PLOT HISTOGRAM\n0,1,2,3: WIDTH 2 GIVES COUNTS 2,2\nLABEL WHETHER HEIGHT IS COUNT OR PROBABILITY\nF08 G05\nG06', field)
    if gid == 'G07':
        return STCORE.unpack_guide('Normal Curve Axes\nLABEL BELL CURVE WITH x AND z\nx=MEAN+z*SD; z=(x-MEAN)/SD\nLABEL z=-3 THROUGH 3; MAP EACH TO x\nCALCULATE x=MEAN+z*SD\nMEAN 40 SD 4: z=1 IS x=44\nNEED MEAN AND SD; NORMALITY NOT PROVED BY LABELS\nS12 G08 G09\nG07', field)
    if gid == 'G08':
        return STCORE.unpack_guide('Empirical Rule\n68 95 99.7; BELL SHAPED\nWITHIN 1,2,3 SD: 68%,95%,99.7%\nOUTSIDE=100-WITHIN; ONE TAIL=OUTSIDE/2\nUSE PERCENT ARITHMETIC\nBEYOND +2 SD ABOUT 2.5%\nAPPROXIMATE; REQUIRES NORMAL/BELL SHAPE\nG07 S10\nG08', field)
    if gid == 'G09':
        return STCORE.unpack_guide('Relative Position\nCOMPARE SCORES FROM DIFFERENT GROUPS\nz=(x-MEAN)/SD FOR EACH\nCOMPARE z VALUES\nUSE Z-SCORE FORMULA TWICE\n44 WITH MEAN40 SD4: z=1\nHIGHER z IS NOT ALWAYS A BETTER OUTCOME\nS12 G07\nG09', field)
    if gid == 'F08':
        return STCORE.unpack_guide('Grouped Frequency Table\nCLASS WIDTH OR NUMBER OF CLASSES\nLOWER UPPER BOUNDARIES f RELATIVE CUMULATIVE\nCOUNT INPUT WEIGHTS INTO NONOVERLAPPING BINS\nUSE TABLE TO DRAW HISTOGRAM\nINTEGER 0..3 WIDTH2: LIMITS0..1,2..3\nMEASUREMENT UNIT DETERMINES BOUNDARIES\nG06 F03\nF08', field)
    if gid == 'D05':
        return STCORE.unpack_guide('Sampling Methods\nHOW WERE SUBJECTS SELECTED?\nCONVENIENCE SYSTEMATIC STRATIFIED CLUSTER RANDOM\nDISTINGUISH EVERY GROUP FROM SELECTED WHOLE GROUPS\nUSE CLASSIFIER\nRANDOM START EVERY 10th: SYSTEMATIC\nSIMPLE RANDOM NEEDS ALL SIZE-n SUBSETS EQUALLY LIKELY\nD03\nD05', field)
    if gid == 'D06':
        return STCORE.unpack_guide('Observational vs Experiment\nDID RESEARCHERS IMPOSE TREATMENT?\nEXPERIMENT: ASSIGNED TREATMENT\nOTHERWISE OBSERVATIONAL\nUSE CLASSIFIER\nSURVEY ONLY: OBSERVATIONAL\nMEASURING IS NOT ASSIGNING TREATMENT\nD05\nD06', field)
    if gid == 'D07':
        return STCORE.unpack_guide('Measurement Levels\nNOMINAL ORDINAL INTERVAL RATIO\nORDER; MEANINGFUL GAPS; TRUE ZERO\nCLASSIFY BY WHAT VALUES MEAN\nUSE DEFINITIONS\nCELSIUS: INTERVAL; WEIGHT: RATIO\nNUMBER LABELS ARE NOT QUANTITATIVE\nD01 D02\nD07', field)
    if gid == 'D08':
        return STCORE.unpack_guide('Statistical vs Practical\nSIGNIFICANCE OR ERROR\np-VALUE COMPARED WITH alpha; EFFECT SIZE\nPRACTICAL IMPORTANCE NEEDS CONTEXT\nUSE SIGNIFICANCE MENU\nTINY EFFECT MAY BE STATISTICALLY SIGNIFICANT\nSTATISTICAL DOES NOT IMPLY PRACTICAL\nD09\nD08', field)
    if gid == 'D09':
        return STCORE.unpack_guide('Law of Large Numbers\nRELATIVE FREQUENCY OVER MANY TRIALS\nINDEPENDENT TRIALS WITH SAME p\nRELATIVE FREQUENCY TENDS TOWARD TRUE p\nUSE RELATIVE FREQUENCY f/n\nMANY FAIR COIN FLIPS: HEAD FRACTION NEAR .5\nA WIN IS NOT DUE AFTER LOSSES\nF02 F04\nD09', field)
    if gid == 'P15':
        return STCORE.unpack_guide('Certain / Impossible\nCAN A VALUE BE A PROBABILITY?\n0<=p<=1\n0 IMPOSSIBLE; 1 CERTAIN; BETWEEN POSSIBLE\nENTER DECIMAL FRACTION OR PERCENT\np=1: CERTAIN\nVALID SINGLE p DOES NOT VALIDATE WHOLE TABLE\nP13 R01\nP15', field)
