# Author: TheEliteCodez
# Practice source records; no solver constants.

def get_record(qid):
    if qid=='PT001': return {'title': 'METRA 38 OR FEWER', 'description': '60 trains, claimed .74 on time; 38 or fewer observed. Question the claimed rate at .05.', 'words': '38 or fewer metra trains at most', 'parameters': 'n=60; p=.74', 'event': 'X<=38', 'command': 'binomcdf(60,.74,38)', 'answer': '.04471712 -> .0447; unusual at .05', 'mistake': 'OR FEWER INCLUDES 38', 'completeness': 'complete', 'id': 'PT001', 'methods': ['B03']}
    if qid=='PT002': return {'title': 'PACKAGING AT LEAST 521', 'description': 'Teacher corrected printed 800 to 700; .68 avoid excess packaging. Check 521 and upper tail.', 'words': 'at least 521 excessive packaging or more', 'parameters': 'n=700; p=.68; x=521', 'event': 'X>=521', 'command': '1-binomcdf(700,.68,520)', 'answer': '.0001200177 -> .0001; 521 unusually high', 'mistake': 'REMOVE THROUGH 520, NOT 521; SOURCE .0002 IS INCORRECT', 'completeness': 'complete; source answer corrected', 'id': 'PT002', 'methods': ['B05']}
    if qid=='PT003': return {'title': 'CHICKENPOX EXACTLY 100', 'description': '123 adults; .90 probability; exactly 100.', 'words': 'chickenpox exactly 100', 'parameters': 'n=123; p=.90', 'event': 'X=100', 'command': 'binompdf(123,.90,100)', 'answer': '.0013', 'mistake': 'POINT PROBABILITY IS NOT LOWER TAIL', 'completeness': 'complete', 'id': 'PT003', 'methods': ['B02']}
    if qid=='PT004': return {'title': 'TABLETS AT MOST ONE', 'description': '26 tablets; defect probability .11; at most one defect.', 'words': 'tablets at most one no more than', 'parameters': 'n=26; p=.11', 'event': 'X<=1', 'command': 'binomcdf(26,.11,1)', 'answer': '.2036', 'mistake': 'AT MOST ONE MEANS ZERO OR ONE', 'completeness': 'complete', 'id': 'PT004', 'methods': ['B03']}
    if qid=='PT005': return {'title': 'WHOLE CLASS RECYCLES', 'description': '23 of 35 students recycle. Whole class is population if describing that class; sample if inferring a larger group.', 'words': 'parameter statistic whole class recycle proportion', 'parameters': '23/35', 'event': 'target population decides', 'command': '23/35', 'answer': '23/35=.6571; parameter or statistic depends on target', 'mistake': 'PERCENTAGE ALONE DOES NOT DECIDE', 'completeness': 'complete', 'id': 'PT005', 'methods': ['D04']}
    if qid=='PT006': return {'title': 'CONVENIENCE SAMPLE', 'description': 'Select people because they are easy to reach or happen to be there.', 'words': 'easiest happen to be there convenient convenience', 'parameters': 'selection by availability', 'event': 'convenience', 'command': 'concept classifier', 'answer': 'CONVENIENCE', 'mistake': 'NOT RANDOM JUST BECAUSE PEOPLE WERE AVAILABLE', 'completeness': 'description only', 'id': 'PT006', 'methods': ['D05']}
    raise ValueError('UNKNOWN PRACTICE ID')
