# Author: Gregory King
# Practice source records; no solver constants.

def get_record(qid):
    if qid=='PT019': return {'title': 'DIE TWICE BOTH TWOS', 'description': 'Fair die rolled twice. First2 AND second2.', 'words': 'die twice first second both twos', 'parameters': 'two independent fair dice', 'event': 'first=2 AND second=2', 'command': '(1/6)*(1/6)', 'answer': '1/36=.0278', 'mistake': 'ORDERED PAIRS, NOT SUM=2', 'completeness': 'complete', 'id': 'PT019', 'methods': ['C07']}
    if qid=='PT020': return {'title': 'POLL SAMPLE PROPORTION', 'description': '1100 randomly selected grade6-8 students;54% enjoy sports.', 'words': 'poll statistic sample proportion categorical', 'parameters': 'sample n=1100;54%', 'event': 'sample proportion', 'command': 'concept classifier', 'answer': 'STATISTIC; SAMPLE PROPORTION', 'mistake': 'CATEGORICAL RESPONSE: NOT SAMPLE MEAN', 'completeness': 'complete', 'id': 'PT020', 'methods': ['D04']}
    if qid=='PT021': return {'title': 'AIRLINE TABLE', 'description': 'Podunk ontime33 late6; Upstate ontime43 late5. Total87; ontime76.', 'words': 'airline upstate podunk given and or without replacement', 'parameters': 'cells [[33,6],[43,5]]', 'event': 'on time GIVEN/AND/OR Upstate', 'command': '43/48;43/87;(76+48-43)/87', 'answer': 'given=.8958;and=.4943;or=.9310;ontime=.8736;both replaced=.7631;not replaced=.7618;not independent', 'mistake': 'ON-TIME TOTAL IS76, NOT39; USE P05/R07 FOR TWO DRAWS', 'completeness': 'complete', 'id': 'PT021', 'methods': ['P14']}
    if qid=='PT022': return {'title': 'EXTREME Z-SCORE', 'description': 'Mean6 hours,SD.5,x=3.', 'words': 'extreme z score unusually low hours', 'parameters': 'mean6;SD.5;x3', 'event': 'z=-6', 'command': '(3-6)/.5', 'answer': '-6.00', 'mistake': 'DIVIDE BY SD, NOT VARIANCE', 'completeness': 'complete', 'id': 'PT022', 'methods': ['S12']}
    if qid=='PT023': return {'title': 'TWO DICE EVENTS', 'description': 'Two fair dice:sum6;first2;both even;doubles AND/OR both even.', 'words': 'two dice doubles first sum even and or', 'parameters': 'n=2;36 ordered pairs', 'event': 'sum=6;first=2;even;doubles AND/OR even', 'command': 'matching ordered pairs /36', 'answer': '5/36;1/6;1/4;1/12;1/3', 'mistake': 'DOUBLES OR EVEN SUBTRACTS OVERLAP', 'completeness': 'complete', 'id': 'PT023', 'methods': ['C07']}
    if qid=='PT024': return {'title': 'FIVE DICE AT LEAST ONE THREE', 'description': 'Five fair dice; probability at least one3.', 'words': 'five dice at least one three complement', 'parameters': 'n=5;face3', 'event': 'at least one3', 'command': '1-(5/6)^5', 'answer': '4651/7776=.5981', 'mistake': '5/6 IS P(NOT3), NOT P(3)', 'completeness': 'complete', 'id': 'PT024', 'methods': ['C07']}
    raise ValueError('UNKNOWN PRACTICE ID')
