# Author: Gregory King
# Practice source records; no solver constants.

def get_record(qid):
    if qid=='PT013': return {'title': 'FIVE COIN FLIPS', 'description': 'X counts tails in five independent fair flips.', 'words': 'five coin flips tails distribution symmetric', 'parameters': 'n=5;p=.5', 'event': 'X=0..5', 'command': 'binompdf(5,.5,k)', 'answer': '1,5,10,10,5,1 over32; mean2.5; SD1.1180', 'mistake': 'SYMMETRIC DOES NOT MEAN UNIFORM', 'completeness': 'complete', 'id': 'PT013', 'methods': ['B11']}
    if qid=='PT014': return {'title': 'SCHOOL FINITE SAMPLE', 'description': '871 students; reported21%; sample80; at least20. Check independence/approximation convention.', 'words': 'school single parent without replacement approximation', 'parameters': 'N=871; n=80; reported p=.21; exact K missing', 'event': 'X>=20 if approximation accepted', 'command': '1-binomcdf(80,.21,19) ONLY IF APPROVED MODEL', 'answer': 'Sampling without replacement is dependent; 80/871 about9.18%; course convention needed', 'mistake': 'DO NOT INVENT K OR UNIVERSAL 5%/10% RULE', 'completeness': 'partial: approximation convention and exact K missing', 'id': 'PT014', 'methods': ['B01']}
    if qid=='PT015': return {'title': 'IMPOSSIBLE AND CERTAIN', 'description': 'Fair die:1..6 certain;7 impossible.', 'words': 'probability zero one impossible certain die', 'parameters': 'p=0 or1', 'event': 'valid endpoint probabilities', 'command': 'classify p', 'answer': '0 impossible;1 certain', 'mistake': 'VALID PROBABILITIES INCLUDE ENDPOINTS', 'completeness': 'complete', 'id': 'PT015', 'methods': ['P15']}
    if qid=='PT016': return {'title': 'STRATIFIED NOT SIMPLE RANDOM', 'description': '100 software and100 hardware engineers; randomly choose20 of each.', 'words': 'stratified random simple random sample every group', 'parameters': '20/100 per stratum; total40', 'event': 'stratified random', 'command': '20/100', 'answer': '.20 each; random, not simple random sample of40', 'mistake': 'OTHER STRATUM COUNTS HAVE ZERO CHANCE', 'completeness': 'complete', 'id': 'PT016', 'methods': ['D05']}
    if qid=='PT017': return {'title': 'GROUPED FREQUENCY TWO PEAKS', 'description': 'Values10..21; frequencies1,3,7,18,10,4,2,7,16,10,6,2. Regroup widths3 and2.', 'words': 'grouped histogram class width bimodal peaks', 'parameters': 'first10; unit1; widths3 or2', 'event': 'group weighted values without expansion', 'command': 'sum f in each class', 'answer': 'width3:11,32,25,18; width2:4,25,14,9,26,8', 'mistake': 'COARSER BINS CAN HIDE TWO PEAKS', 'completeness': 'complete', 'id': 'PT017', 'methods': ['F08']}
    if qid=='PT018': return {'title': 'DEFECTIVE COILS REPLACED', 'description': '12 defective and88 good; select3 with replacement.', 'words': 'coils with replacement at least one defective', 'parameters': 'n=3;p=.12', 'event': 'X=3; X>=1', 'command': 'binompdf(3,.12,3);1-binomcdf(3,.12,0)', 'answer': 'P(3)=.001728; P(>=1)=.318528; distribution .681472,.278784,.038016,.001728', 'mistake': 'REPLACEMENT KEEPS SAME p', 'completeness': 'complete', 'id': 'PT018', 'methods': ['B02']}
    raise ValueError('UNKNOWN PRACTICE ID')
