# Author: TheEliteCodez
# Practice source records; no solver constants.

def get_record(qid):
    if qid=='PT007': return {'title': 'TEST SCORES RELATIVE POSITION', 'description': 'Compare x=44,mean40,SD4 with x=283.4,mean260,SD26. Label both x/z axes.', 'words': 'relative position test scores normal curves z score', 'parameters': '44,40,4; 283.4,260,26', 'event': 'z1>z2', 'command': '(44-40)/4; (283.4-260)/26', 'answer': 'z1=1; z2=.9; first score higher relative', 'mistake': 'DO NOT SNAP .9 TO 1; G07 LABELS AXES', 'completeness': 'complete', 'id': 'PT007', 'methods': ['G09']}
    if qid=='PT008': return {'title': 'MEN AND WOMEN RAW LISTS', 'description': 'Men:120,77,89,97,124,68,72,96. Women:115,86,49,56,78,76,78,95. Compare and draw side-by-side boxes.', 'words': 'compare two lists men women quartiles boxplots', 'parameters': 'two lists of 8', 'event': 'compare center and spread', 'command': '1-Var Stats for each list', 'answer': 'MEN mean92.875 SD20.8836 var436.125 Q1=74.5 Q3=108.5; WOMEN mean79.125 SD20.8425 var434.410714 Q1=66 Q3=90.5', 'mistake': 'SOURCE SD/VAR VALUES INCORRECT; USE SUPPLIED RAW LISTS', 'completeness': 'complete; source answers corrected', 'id': 'PT008', 'methods': ['S16']}
    if qid=='PT009': return {'title': 'OUTSIDE TWO SD', 'description': 'For a bell-shaped distribution find percent outside +/-2 SD.', 'words': 'more than two standard deviations outside two sd empirical bell shaped', 'parameters': 'normal/bell shaped; 2 SD', 'event': 'outside both tails', 'command': '100%-95%', 'answer': 'about 5% total; 2.5% per tail', 'mistake': 'TWO TAILS NOT ONE', 'completeness': 'complete', 'id': 'PT009', 'methods': ['G08']}
    if qid=='PT010': return {'title': 'LAW OF LARGE NUMBERS', 'description': 'Independent repeated trials: relative frequency tends toward true probability.', 'words': 'law large numbers relative frequency repetitions', 'parameters': 'independent same-probability trials', 'event': 'long-run relative frequency', 'command': 'f/n', 'answer': 'Relative frequency tends toward p', 'mistake': 'NO GUARANTEE OF EXACT EQUALITY OR A WIN BEING DUE', 'completeness': 'complete', 'id': 'PT010', 'methods': ['D09']}
    if qid=='PT011': return {'title': 'RACKET TABLE', 'description': 'Wood:5 defective,95 good. Graphite:10 defective,90 good. Find wood OR defective.', 'words': 'racket table wood graphite or defective', 'parameters': 'cells [[5,95],[10,90]]', 'event': 'wood OR defective', 'command': '(100+15-5)/200', 'answer': '.55', 'mistake': 'SUBTRACT OVERLAP 5', 'completeness': 'complete', 'id': 'PT011', 'methods': ['P14']}
    if qid=='PT012': return {'title': 'BAG COLORS', 'description': '7 red,4 blue,1 green. Not blue, blue OR red, two blue/green without replacement.', 'words': 'bag colors without replacement blue green red', 'parameters': 'N=12; K=4 blue or1 green; n=2', 'event': 'X=2 for selected color', 'command': '(4/12)*(3/11)', 'answer': 'two blue=1/11; two green=0; not blue=2/3; blue OR red=11/12', 'mistake': 'SECOND DRAW DENOMINATOR 11; CATEGORY PARTS USE P01', 'completeness': 'complete', 'id': 'PT012', 'methods': ['R07']}
    raise ValueError('UNKNOWN PRACTICE ID')
