# On-demand course records.

def get_record(qid):
    if qid=='Q001': return {'id': 'Q001', 'title': 'DELIVERIES: FREQUENCY MEAN', 'description': 'Course question: DELIVERIES: FREQUENCY MEAN. deliveries values3,6,9,12; frequencies1,2,6,5', 'words': 'deliveries: frequency mean deliveries values3,6,9,12; frequencies1,2,6,5', 'methods': ['F05'], 'parameters': 'deliveries values3,6,9,12; frequencies1,2,6,5', 'event': 'deliveries values3,6,9,12; frequencies1,2,6,5', 'command': 'sum(x*f)/sum(f)', 'answer': '129/14=9.2143; n=14', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q002': return {'id': 'Q002', 'title': 'RAIN: MEDIAN AND MODE', 'description': 'Course question: RAIN: MEDIAN AND MODE. rain values6,7,8,9,10; frequencies5,6,3,4,2', 'words': 'rain: median and mode rain values6,7,8,9,10; frequencies5,6,3,4,2', 'methods': ['F06'], 'parameters': 'rain values6,7,8,9,10; frequencies5,6,3,4,2', 'event': 'rain values6,7,8,9,10; frequencies5,6,3,4,2', 'command': 'median via cumulative positions;mode highest f', 'answer': 'n=20; positions 10,11=7; mode=7', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q003': return {'id': 'Q003', 'title': 'ROULETTE 0 AND 00', 'description': 'Course question: ROULETTE 0 AND 00. wheel 0,00,1..36', 'words': 'roulette 0 and 00 wheel 0,00,1..36', 'methods': ['P01'], 'parameters': 'wheel 0,00,1..36', 'event': 'wheel 0,00,1..36', 'command': 'favorable/38', 'answer': '38 spaces; single=1/38; odd=9/19', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q004': return {'id': 'Q004', 'title': 'DIE THEN COIN', 'description': 'Course question: DIE THEN COIN. fair six-sided die and independent fair coin', 'words': 'die then coin fair six-sided die and independent fair coin', 'methods': ['C05'], 'parameters': 'fair six-sided die and independent fair coin', 'event': 'fair six-sided die and independent fair coin', 'command': 'favorable/12', 'answer': '12 outcomes; H=1/2; 6=1/6; 3 OR H=7/12; 6T=1/12', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q005': return {'id': 'Q005', 'title': 'SCRATCHED LENSES', 'description': 'Course question: SCRATCHED LENSES. scratch count730,total1589; equivalent5840/12712', 'words': 'scratched lenses scratch count730,total1589; equivalent5840/12712', 'methods': ['F02'], 'parameters': 'scratch count730,total1589; equivalent5840/12712', 'event': 'scratch count730,total1589; equivalent5840/12712', 'command': '730/1589', 'answer': '5840/12712=730/1589=0.459 (3 places)', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q006': return {'id': 'Q006', 'title': 'LONG-RUN PROPORTION', 'description': 'Course question: LONG-RUN PROPORTION. identical repeated conditions; long-run event proportion', 'words': 'long-run proportion identical repeated conditions; long-run event proportion', 'methods': ['F02'], 'parameters': 'identical repeated conditions; long-run event proportion', 'event': 'identical repeated conditions; long-run event proportion', 'command': 'See method F02 for formula / classification', 'answer': 'Relative frequency estimates event probability', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q007': return {'id': 'Q007', 'title': 'VALID PROBABILITY?', 'description': 'Course question: VALID PROBABILITY?. tested probability value missing', 'words': 'valid probability? tested probability value missing', 'methods': ['P13'], 'parameters': 'tested probability value missing', 'event': 'tested probability value missing', 'command': 'See method P13 for formula / classification', 'answer': 'Missing value; valid iff 0<=p<=1', 'mistake': 'Preserve missing source: tested value missing', 'completeness': 'partial: tested value missing'}
    if qid=='Q008': return {'id': 'Q008', 'title': '52-CARD DECK', 'description': 'Course question: 52-CARD DECK. standard52-card deck;4S;S OR D;rank<3', 'words': '52-card deck standard52-card deck;4S;S OR D;rank<3', 'methods': ['P01'], 'parameters': 'standard52-card deck;4S;S OR D;rank<3', 'event': 'standard52-card deck;4S;S OR D;rank<3', 'command': 'See method P01 for formula / classification', 'answer': '4S=.0192; S OR D=.5000; ace or 2=.1538', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q009': return {'id': 'Q009', 'title': 'GRADE TABLE: MALE', 'description': 'Course question: GRADE TABLE: MALE. 36 male of81', 'words': 'grade table: male 36 male of81', 'methods': ['P14'], 'parameters': '36 male of81', 'event': '36 male of81', 'command': '36/81', 'answer': '36/81=.4444', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q010': return {'id': 'Q010', 'title': 'BOTH INTOXICATED', 'description': 'Course question: BOTH INTOXICATED. 61 both intoxicated of979', 'words': 'both intoxicated 61 both intoxicated of979', 'methods': ['P12'], 'parameters': '61 both intoxicated of979', 'event': '61 both intoxicated of979', 'command': '61/979', 'answer': '61/979=.0623; whole total, not given group', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    raise ValueError('UNKNOWN QUESTION ID')
