# Author: TheEliteCodez
# On-demand course records.

def get_record(qid):
    if qid=='Q021': return {'id': 'Q021', 'title': 'SCORE EXPECTED VALUE', 'description': 'Course question: SCORE EXPECTED VALUE. P first column .32,.01,.08,.35,.05,.17,.02; scores1,2,6,8,9,12,13', 'words': 'score expected value P first column .32,.01,.08,.35,.05,.17,.02; scores1,2,6,8,9,12,13', 'methods': ['R02'], 'parameters': 'P first column .32,.01,.08,.35,.05,.17,.02; scores1,2,6,8,9,12,13', 'event': 'P first column .32,.01,.08,.35,.05,.17,.02; scores1,2,6,8,9,12,13', 'command': 'sum(score*P)', 'answer': 'SUM(score*probability)=6.37', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q022': return {'id': 'Q022', 'title': 'WEBCAM DEFECT TABLE', 'description': 'Course question: WEBCAM DEFECT TABLE. X0..5;P=.904,.047,.024,.018,.005,.002', 'words': 'webcam defect table X0..5;P=.904,.047,.024,.018,.005,.002', 'methods': ['R04'], 'parameters': 'X0..5;P=.904,.047,.024,.018,.005,.002', 'event': 'X0..5;P=.904,.047,.024,.018,.005,.002', 'command': '1-P(0);sum(P2..P4)', 'answer': '.904; 1-.904=.096; 2..4=.047; exactly 1=.047 unusual at .05', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q023': return {'id': 'Q023', 'title': 'RAFFLE EV IS WIN %?', 'description': 'Course question: RAFFLE EV IS WIN %?. claim expected$.85 means85% win', 'words': 'raffle ev is win %? claim expected$.85 means85% win', 'methods': ['R02'], 'parameters': 'claim expected$.85 means85% win', 'event': 'claim expected$.85 means85% win', 'command': 'See method R02 for formula / classification', 'answer': 'FALSE: dollars are not a probability', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q024': return {'id': 'Q024', 'title': 'GAME EV IS WIN %?', 'description': 'Course question: GAME EV IS WIN %?. claim expected$.40 means40% win', 'words': 'game ev is win %? claim expected$.40 means40% win', 'methods': ['R02'], 'parameters': 'claim expected$.40 means40% win', 'event': 'claim expected$.40 means40% win', 'command': 'See method R02 for formula / classification', 'answer': 'FALSE: long-run average dollars per play', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q025': return {'id': 'Q025', 'title': '8 CAMERAS 5 DEFECTIVE', 'description': 'Course question: 8 CAMERAS 5 DEFECTIVE. N8,K5,n2;without replacement', 'words': '8 cameras 5 defective N8,K5,n2;without replacement without replacement', 'methods': ['R07'], 'parameters': 'N8,K5,n2;without replacement', 'event': 'N8,K5,n2;without replacement', 'command': 'C(5,k)*C(3,2-k)/C(8,2)', 'answer': 'P(0..2)=3/28,15/28,5/14; E=5/4', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q026': return {'id': 'Q026', 'title': '6 CAMERAS 4 DEFECTIVE', 'description': 'Course question: 6 CAMERAS 4 DEFECTIVE. N6,K4,n2;without replacement', 'words': '6 cameras 4 defective N6,K4,n2;without replacement without replacement', 'methods': ['R07'], 'parameters': 'N6,K4,n2;without replacement', 'event': 'N6,K4,n2;without replacement', 'command': 'C(4,k)*C(2,2-k)/C(6,2)', 'answer': '.0667,.5333,.4000; E=1.3333', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q027': return {'id': 'Q027', 'title': '17 PENS 5 DEFECTIVE', 'description': 'Course question: 17 PENS 5 DEFECTIVE. N17,K5,n3;without replacement', 'words': '17 pens 5 defective N17,K5,n3;without replacement without replacement', 'methods': ['R07'], 'parameters': 'N17,K5,n3;without replacement', 'event': 'N17,K5,n3;without replacement', 'command': 'C(5,k)*C(12,3-k)/C(17,3)', 'answer': '11/34,33/68,3/17,1/68; E=15/17', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q028': return {'id': 'Q028', 'title': 'FOUR SUIT GUESSES', 'description': 'Course question: FOUR SUIT GUESSES. 4 suit guesses with replacement;win270;lose3', 'words': 'four suit guesses 4 suit guesses with replacement;win270;lose3', 'methods': ['R08'], 'parameters': '4 suit guesses with replacement;win270;lose3', 'event': '4 suit guesses with replacement;win270;lose3', 'command': 'sum(net*P);sqrt(sum(net^2*P)-mu^2)', 'answer': 'P(win)=1/256; E=-1.93359375; SD=17.0291422', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q029': return {'id': 'Q029', 'title': 'MARBLE PRIZES AND COST', 'description': 'Course question: MARBLE PRIZES AND COST. 3gold,9silver,30black;grossprizes6,2,0;cost1', 'words': 'marble prizes and cost 3gold,9silver,30black;grossprizes6,2,0;cost1', 'methods': ['R08'], 'parameters': '3gold,9silver,30black;grossprizes6,2,0;cost1', 'event': '3gold,9silver,30black;grossprizes6,2,0;cost1', 'command': 'sum(net*P)', 'answer': 'NET outcomes 5,1,-1; P=3/42,9/42,30/42; E=-1/7', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q030': return {'id': 'Q030', 'title': 'INSURER EXPECTATION', 'description': 'Course question: INSURER EXPECTATION. survival.999363;premium259;deathbenefit206000;insurer perspective', 'words': 'insurer expectation survival.999363;premium259;deathbenefit206000;insurer perspective', 'methods': ['R08'], 'parameters': 'survival.999363;premium259;deathbenefit206000;insurer perspective', 'event': 'survival.999363;premium259;deathbenefit206000;insurer perspective', 'command': '259-206000*(1-.999363)', 'answer': '259-206000*(1-.999363)=127.78', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    raise ValueError('UNKNOWN QUESTION ID')
