# On-demand course records.

def get_record(qid):
    if qid=='Q031': return {'id': 'Q031', 'title': 'RAFFLE BUYER / PTO', 'description': 'Course question: RAFFLE BUYER / PTO. tickets240;price2;prize80;buy8', 'words': 'raffle buyer / pto tickets240;price2;prize80;buy8', 'methods': ['R08'], 'parameters': 'tickets240;price2;prize80;buy8', 'event': 'tickets240;price2;prize80;buy8', 'command': 'expected prize-ticket cost', 'answer': '-1.67; eight=-13.33; PTO one=1.67; all=400', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q032': return {'id': 'Q032', 'title': 'REPLACED CARDS BINOMIAL?', 'description': 'Course question: REPLACED CARDS BINOMIAL?. 15 draws replaced/reshuffled;count hearts;p13/52', 'words': 'replaced cards binomial? 15 draws replaced/reshuffled;count hearts;p13/52', 'methods': ['B01'], 'parameters': '15 draws replaced/reshuffled;count hearts;p13/52', 'event': '15 draws replaced/reshuffled;count hearts;p13/52', 'command': 'See method B01 for formula / classification', 'answer': 'TRUE; n=15 p=13/52; independent draws', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q033': return {'id': 'Q033', 'title': 'BINOMIAL TAIL SYMMETRY?', 'description': 'Course question: BINOMIAL TAIL SYMMETRY?. n20;p unspecified;P(X<4)=P(X>16)?', 'words': 'binomial tail symmetry? n20;p unspecified;P(X<4)=P(X>16)?', 'methods': ['B12'], 'parameters': 'n20;p unspecified;P(X<4)=P(X>16)?', 'event': 'n20;p unspecified;P(X<4)=P(X>16)?', 'command': 'See method B12 for formula / classification', 'answer': 'FALSE generally; matching opposite tails requires p=.5', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q034': return {'id': 'Q034', 'title': 'CHICKENPOX 123 ADULTS', 'description': 'Course question: CHICKENPOX 123 ADULTS. n123;p.9;mean,SD;100unusual;P(X=100)', 'words': 'chickenpox 123 adults n123;p.9;mean,SD;100unusual;P(X=100)', 'methods': ['B13'], 'parameters': 'n123;p.9;mean,SD;100unusual;P(X=100)', 'event': 'n123;p.9;mean,SD;100unusual;P(X=100)', 'command': 'binompdf(123,.9,100);np;sqrt(np(1-p))', 'answer': 'mu=110.7000; SD=3.3272; 100 unusually low; P(100)=.0013', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q035': return {'id': 'Q035', 'title': 'THREE FLIPS COUNT HEADS', 'description': 'Course question: THREE FLIPS COUNT HEADS. n3;p.5;countheads;fulltable;P(X<=2)', 'words': 'three flips count heads n3;p.5;countheads;fulltable;P(X<=2)', 'methods': ['B11'], 'parameters': 'n3;p.5;countheads;fulltable;P(X<=2)', 'event': 'n3;p.5;countheads;fulltable;P(X<=2)', 'command': 'binompdf(3,.5,k);binomcdf(3,.5,2)', 'answer': '1/8,3/8,3/8,1/8; symmetric; mu=1.500 heads; sigma=.866; P(<=2)=7/8', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q036': return {'id': 'Q036', 'title': 'DEPENDENT FLIGHT DELAYS', 'description': 'Course question: DEPENDENT FLIGHT DELAYS. one flight delay increases next delay probability', 'words': 'dependent flight delays one flight delay increases next delay probability', 'methods': ['B01'], 'parameters': 'one flight delay increases next delay probability', 'event': 'one flight delay increases next delay probability', 'command': 'See method B01 for formula / classification', 'answer': 'NOT BINOMIAL: flights explicitly dependent', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q037': return {'id': 'Q037', 'title': '8 CAMERAS 3 DEFECTIVE', 'description': 'Course question: 8 CAMERAS 3 DEFECTIVE. N8,K3,n2;without replacement', 'words': '8 cameras 3 defective N8,K3,n2;without replacement without replacement', 'methods': ['R07'], 'parameters': 'N8,K3,n2;without replacement', 'event': 'N8,K3,n2;without replacement', 'command': 'C(3,k)*C(5,2-k)/C(8,2)', 'answer': '5/14,15/28,3/28; E=3/4', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q038': return {'id': 'Q038', 'title': '26 FLU CALLERS', 'description': 'Course question: 26 FLU CALLERS. n26;p.16;later part missing', 'words': '26 flu callers n26;p.16;later part missing', 'methods': ['B01'], 'parameters': 'n26;p.16;later part missing', 'event': 'n26;p.16;later part missing', 'command': 'See method B01 for formula / classification', 'answer': 'Binomial(26,.16), assuming independence; second part missing', 'mistake': 'Preserve missing source: later part missing', 'completeness': 'partial: later part missing'}
    if qid=='Q039': return {'id': 'Q039', 'title': '18 PEOPLE ELECTRICITY', 'description': 'Course question: 18 PEOPLE ELECTRICITY. n18;p.08;X=3;X<3;X>=3;2<=X<=5', 'words': '18 people electricity n18;p.08;X=3;X<3;X>=3;2<=X<=5', 'methods': ['B02'], 'parameters': 'n18;p.08;X=3;X<3;X>=3;2<=X<=5', 'event': 'n18;p.08;X=3;X<3;X>=3;2<=X<=5', 'command': 'PDF(3);CDF(2);1-CDF(2);CDF(5)-CDF(1)', 'answer': 'Binomial(18,.08); .1196,.8298,.1702,.4260', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    if qid=='Q040': return {'id': 'Q040', 'title': 'BLOOD TYPE STANDARD DEV', 'description': 'Course question: BLOOD TYPE STANDARD DEV. n19;p.108;SD', 'words': 'blood type standard dev n19;p.108;SD', 'methods': ['B09'], 'parameters': 'n19;p.108;SD', 'event': 'n19;p.108;SD', 'command': 'sqrt(19*.108*.892)', 'answer': 'SQRT(19*.108*.892)=1.3529168489', 'mistake': 'Use the stated event and denominator; see method for common mistakes.', 'completeness': 'preserved description; original wording may be abbreviated'}
    raise ValueError('UNKNOWN QUESTION ID')
