# Author: Gregory King
# Quiz 3 reference text loads only when selected.
import STCORE as c

EXAMPLES=(
 ('QZ301 COVID GRAPH', 'GRAPH IMAGE MISSING: CANNOT IDENTIFY ITS SPECIFIC DISTORTION. IF THE AXIS LISTS VACCINATION STATUS, IT IS A BAR GRAPH OF CATEGORIES. CHECK ZERO BASELINE, EVEN SCALE, LABELS AND CASES PER 100000 RESIDENTS. DO NOT INVENT THE MISSING VALUES.'),
 ('QZ302 URBAN / RURAL', 'HOME 4 > 6 COMPARE LISTS. URBAN: 24,23.5,25,27,39,22.5,28,24. RURAL: 18,20,24,24,20,21,22,20. SAMPLE STATISTICS: URBAN MEAN 26.625, MODE 24, MIDRANGE 30.75, RANGE 16.5, VARIANCE 28.3393, SD 5.3235. FIVE NUMBERS: 22.5,23.75,24.5,27.5,39. RURAL MEAN 21.125, MODE 20, MIDRANGE 21, RANGE 6, VARIANCE 4.4107, SD 2.1002. FIVE NUMBERS: 18,20,20.5,23,24. URBAN HAS HIGHER CENTERS AND MORE VARIATION. UNITS: HUNDREDS OF GALLONS PER YEAR; VARIANCE HAS SQUARED UNITS. THIS ALONE DOES NOT PROVE A CAUSAL EFFECT OR STATISTICAL SIGNIFICANCE. COMPARE MENU 4: BOXPLOT VALUES. URBAN MODIFIED WHISKERS 22.5 TO 28; OUTLIER 39. ORDINARY WHISKERS 22.5 TO 39. RURAL WHISKERS 18 TO 24; NO OUTLIERS. DRAW BOTH ON SAME SCALE. COMPARE MENU 6: USUAL LIMITS, CHOOSE STRICT. URBAN 15.9781 TO 37.2719; 39 HIGH. RURAL 16.9247 TO 25.3253; NONE UNUSUAL.'),
 ('QZ303 PLANT Z-SCORES', 'HOME 5 > 7. A: x=24.6, MEAN=21, SD=9. B: x=6.4, MEAN=4.7, SD=1.2. z A=.4000; z B=1.4167. SUCCULENT B IS HIGHER RELATIVE TO ITS GROUP. NEXT MENU 1 LABELS BOTH AXES WITHOUT REENTRY. z TICKS -3,-2,-1,0,1,2,3. TOMATO x TICKS -6,3,12,21,30,39,48. SUCCULENT x TICKS 1.1,2.3,3.5,4.7,5.9,7.1,8.3. DRAW TWO BELLS CENTERED AT z=0; MARK EACH OBSERVATION AT ITS z.'),
 ('QZ304 POLAR BEARS', 'HOME 5 > 1. MEAN 42, SD 3. OPTION 5 GIVES MIN USUAL 36 AND MAX USUAL 48. OPTION 7 SELECTS BOUNDARY RULE: CHOOSE INCLUSIVE FOR THE PRINTED x<=36 OR x>=48. QUESTION 2 INSTEAD USES STRICT BOUNDARIES. CHECK 37: NOT UNUSUAL. OPTION 1 GIVES z=(37-42)/3=-1.6667. BEAR COUNTS ARE DISCRETE. OPTION 3 AXES: z=-3,-2,-1,0,1,2,3 MATCHES x=33,36,39,42,45,48,51. MARK 37 BETWEEN z=-2 AND -1. A NORMAL CURVE HERE IS A MODEL; COUNTS REMAIN DISCRETE.'))

GRAPH_GUIDE='BAR GRAPH: COMPARES CATEGORIES, SUCH AS VACCINATION STATUS. HISTOGRAM: NUMERICAL DATA GROUPED INTO INTERVALS IN NUMERIC ORDER, USUALLY TOUCHING. A TRUNCATED BAR AXIS CAN EXAGGERATE DIFFERENCES; REDRAW BARS FROM ZERO. CHECK EQUAL SCALE SPACING, AXIS BREAKS, TIME SPANS, UNITS AND MISSING LABELS. PICTURE AREA OR 3D EFFECTS CAN DISTORT BAR HEIGHTS. USE PLAIN BARS, CLEAR LABELS, CONSISTENT WIDTHS AND THE SAME SCALE FOR COMPARISONS. LABEL RATES AS CASES PER 100000, NOT RAW COUNTS. HISTOGRAMS WITH UNEQUAL BIN WIDTHS REQUIRE DENSITY HEIGHTS SO AREAS REPRESENT FREQUENCIES. NEED THE ACTUAL GRAPH TO IDENTIFY ITS SPECIFIC PROBLEM.'


def quiz_menu():
    while True:
        key=c.menu('QUIZ 3 / GRAPHS',[(str(i+1),title) for i,(title,body) in enumerate(EXAMPLES)]+[('5','MISLEADING GRAPH GUIDE')])
        if key=='0': return
        if key=='5': c.call('STSTUDY','definition_pages','GRAPH INTERPRETATION',GRAPH_GUIDE)
        else:
            title,body=EXAMPLES[int(key)-1]
            c.call('STSTUDY','definition_pages',title,body)
