# StatScholar - TI-84 Python Statistics Tutor
# Author: Gregory King
# Date: 2026-09-20
# Copyright (c) 2026 Gregory King
# SPDX-License-Identifier: LicenseRef-StatScholar-Free-Use-No-Sale-1.0
#
# License terms: see LICENSE or STAT1.py.

# STSTUDY - on-demand reference module.
import STCORE

DEFINITIONS = [('population', 'ENTIRE GROUP THE STUDY WANTS TO DESCRIBE.'), ('sample', 'SUBSET OF POPULATION ACTUALLY OBSERVED.'), ('parameter', 'NUMBER DESCRIBING A POPULATION.'), ('statistic', 'NUMBER DESCRIBING A SAMPLE.'), ('qualitative', 'CATEGORICAL DATA; LABELS OR GROUPS.'), ('quantitative', 'NUMERICAL COUNTS OR MEASUREMENTS.'), ('discrete', 'COUNTABLE SEPARATE NUMERICAL VALUES.'), ('continuous', 'MEASURED VALUES THAT CAN VARY THROUGH AN INTERVAL.'), ('frequency', 'NUMBER OF TIMES A VALUE OR CATEGORY OCCURS.'), ('relative frequency', 'FREQUENCY DIVIDED BY TOTAL n.'), ('cumulative frequency', 'RUNNING TOTAL OF FREQUENCIES.'), ('mean', 'SUM OF VALUES DIVIDED BY n.'), ('median', 'MIDDLE ORDERED VALUE; 50TH PERCENTILE.'), ('mode', 'MOST FREQUENT VALUE.'), ('range', 'MAXIMUM MINUS MINIMUM.'), ('q1', 'FIRST QUARTILE; ABOUT LOWEST 25%.'), ('q3', 'THIRD QUARTILE; ABOUT 75% AT OR BELOW.'), ('iqr', 'Q3-Q1; SPREAD OF MIDDLE 50%.'), ('outlier', 'VALUE UNUSUALLY FAR FROM OTHERS.'), ('right skew', 'LONG TAIL TO RIGHT.'), ('left skew', 'LONG TAIL TO LEFT.'), ('sample space', 'SET OF ALL POSSIBLE OUTCOMES.'), ('event', 'SET OF OUTCOMES FROM SAMPLE SPACE.'), ('complement', 'ALL OUTCOMES NOT IN EVENT; 1-P(E).'), ('union', 'A OR B.'), ('intersection', 'A AND B.'), ('mutually exclusive', 'EVENTS CANNOT OCCUR TOGETHER.'), ('independent', 'ONE EVENT DOES NOT CHANGE PROBABILITY OF OTHER.'), ('conditional probability', 'PROBABILITY OF A GIVEN B.'), ('random variable', 'NUMERIC VALUE ASSIGNED TO RANDOM OUTCOME.'), ('expected value', 'LONG-RUN MEAN; SUM[x*P(x)].'), ('binomial distribution', 'FIXED n, TWO OUTCOMES, SAME p, INDEPENDENT.'), ('combination', 'SELECTION WHERE ORDER DOES NOT MATTER; nCr.'), ('permutation', 'ARRANGEMENT WHERE ORDER MATTERS; nPr.'), ('z score', 'NUMBER OF SDs A VALUE IS FROM MEAN.')]

SAMPLING_DEFINITIONS = [
    ('simple random sample', 'EVERY POSSIBLE SUBGROUP OF SIZE n HAS THE SAME CHANCE OF SELECTION. NUMBER EVERYONE, THEN HAVE A COMPUTER RANDOMLY PICK n DISTINCT NUMBERS. EQUAL INDIVIDUAL CHANCES ALONE DO NOT GUARANTEE A SIMPLE RANDOM SAMPLE.'),
    ('random sample', 'EVERY INDIVIDUAL IN THE POPULATION HAS AN EQUAL CHANCE OF BEING IN THE SAMPLE. FOR A SIMPLE RANDOM SAMPLE, EVERY POSSIBLE SUBGROUP OF SIZE n MUST ALSO BE EQUALLY LIKELY.'),
    ('systematic sample', 'CHOOSE A RANDOM START, THEN SELECT EVERY kth MEMBER OF THE POPULATION LIST. EXAMPLE: RANDOMLY START AT 4, THEN TAKE 4, 14, 24, ETC. REPEATING PATTERNS IN THE LIST CAN BIAS THE SAMPLE.'),
    ('convenience sample', 'SELECT PEOPLE WHO ARE EASIEST TO REACH. EXAMPLE: ASK NEARBY FRIENDS. THE SAMPLE MAY NOT REPRESENT THE POPULATION.'),
    ('stratified sample', 'DIVIDE THE POPULATION INTO STRATA: GROUPS ALIKE WITHIN EACH GROUP BUT DIFFERENT BETWEEN GROUPS. RANDOMLY SAMPLE FROM EVERY GROUP. IN PROPORTIONATE STRATIFIED SAMPLING, USE EACH GROUP IN THE SAME PROPORTION AS IN THE POPULATION. EXAMPLE: 60% FRESHMEN IN THE POPULATION, SO 60% OF THE SAMPLE ARE FRESHMEN.'),
    ('cluster sample', 'DIVIDE THE POPULATION INTO GROUPS CALLED CLUSTERS. RANDOMLY SELECT SOME GROUPS, THEN SURVEY EVERYONE IN THE SELECTED GROUPS. EXAMPLE: SELECT SOME CLASSROOMS AND SURVEY ALL THEIR STUDENTS. SAMPLING ONLY SOME PEOPLE WITHIN SELECTED CLUSTERS IS MULTISTAGE SAMPLING.'),
    ('bias', 'A METHOD SYSTEMATICALLY FAVORS SOME RESULTS. A BAD SAMPLING FRAME CAN LEAVE PEOPLE OUT OR OVERREPRESENT OTHERS, SO THE SAMPLE DOES NOT REPRESENT THE POPULATION CHARACTERISTICS. BIASED QUESTIONS AND NONRESPONSE CAN ALSO CAUSE BIAS.')]

MEASUREMENT_DEFINITIONS = [
    ('nominal', 'CATEGORIES WITH NO NATURAL ORDER. EXAMPLES: BLOOD TYPE OR EYE COLOR. NUMBER LABELS DO NOT MAKE THE DATA QUANTITATIVE.'),
    ('ordinal', 'ORDERED CATEGORIES, BUT DIFFERENCES BETWEEN RANKS ARE NOT MEANINGFUL MEASURED GAPS. EXAMPLE: POOR, FAIR, GOOD, EXCELLENT.'),
    ('interval', 'ORDERED NUMERICAL VALUES WITH MEANINGFUL EQUAL DIFFERENCES, BUT NO TRUE ZERO. EXAMPLE: CELSIUS TEMPERATURE. 20 DEGREES C IS NOT TWICE AS HOT AS 10 DEGREES C.'),
    ('ratio', 'NUMERICAL VALUES WITH MEANINGFUL EQUAL DIFFERENCES AND A TRUE ZERO THAT MEANS NONE OF THE QUANTITY. RATIOS ARE MEANINGFUL. EXAMPLES: WEIGHT, HEIGHT, ELAPSED TIME. 20 MINUTES IS TWICE 10 MINUTES.')]

STUDY_DEFINITIONS = [
    ('sampling error', 'CHANCE DIFFERENCE BETWEEN A SAMPLE STATISTIC AND THE POPULATION PARAMETER BECAUSE ONLY A SAMPLE WAS OBSERVED. IT CAN OCCUR EVEN WITH A WELL-DESIGNED RANDOM SAMPLE.'),
    ('non-sampling error', 'ERROR FROM CAUSES OTHER THAN RANDOM SAMPLE VARIATION: BAD MEASUREMENTS, DATA ENTRY MISTAKES, UNDERCOVERAGE, NONRESPONSE, OR MISLEADING QUESTIONS. IT CAN OCCUR IN A SAMPLE OR A CENSUS.'),
    ('statistically significant', 'THE OBSERVED RESULT WOULD BE SUFFICIENTLY UNLIKELY UNDER THE NULL HYPOTHESIS. A TEST DECLARES SIGNIFICANCE WHEN ITS p-VALUE IS AT OR BELOW THE CHOSEN SIGNIFICANCE LEVEL alpha. THIS DOES NOT SHOW THAT THE EFFECT IS LARGE OR IMPORTANT.'),
    ('practically significant', 'THE EFFECT IS LARGE OR IMPORTANT ENOUGH TO MATTER IN REAL LIFE. CONSIDER ITS SIZE, COSTS, AND CONTEXT. A TINY EFFECT CAN BE STATISTICALLY SIGNIFICANT IN A VERY LARGE SAMPLE WITHOUT BEING PRACTICALLY IMPORTANT.'),
    ('outlier', 'A VALUE UNUSUALLY FAR FROM THE OTHER VALUES. COMMON BOXPLOT RULE: BELOW Q1-1.5*IQR OR ABOVE Q3+1.5*IQR, WHERE IQR=Q3-Q1. AN OUTLIER MAY BE REAL OR AN ERROR; IT IS NOT AUTOMATICALLY A MISTAKE.')]

BIAS_DEFINITIONS = [
    ('voluntary response', 'PEOPLE CHOOSE TO JOIN THE SAMPLE, SUCH AS CALLING A RADIO SHOW. STRONG OPINIONS MAY BE OVERREPRESENTED. MORE RESPONSES DO NOT REMOVE THIS BIAS.'),
    ('undercoverage', 'THE SAMPLING FRAME LEAVES OUT PART OF THE TARGET POPULATION. RANDOMLY SAMPLING COLLEGE MEMBERS DOES NOT REPRESENT ALL US ADULTS.'),
    ('nonresponse bias', 'SELECTED PEOPLE DO NOT RESPOND, AND RESPONDENTS DIFFER SYSTEMATICALLY FROM NONRESPONDENTS. LOW RESPONSE ALONE DOES NOT MEASURE THE BIAS.'),
    ('quota sampling', 'FILL SPECIFIED COUNTS FROM POPULATION SUBGROUPS. RANDOM SELECTION WITHIN GROUPS IS NOT REQUIRED. STRATIFIED RANDOM SAMPLING DOES REQUIRE IT.'),
    ('cumulative relative frequency', 'RUNNING COUNT DIVIDED BY TOTAL COUNT. ENDS AT 1; CUMULATIVE FREQUENCY IS A COUNT AND ENDS AT n. USE UNROUNDED COUNTS BEFORE ROUNDING.')]


def definition_pages(title, definition):
    return STCORE.call('STPAGE','text_pages',title,definition)


def definition_list(title, entries):
    while True:
        key = STCORE.menu(title, [(str(i+1), entry[0].upper())
                                 for i, entry in enumerate(entries)])
        if key == '0': return
        term, definition = entries[int(key)-1]
        definition_pages(term, definition)

DEFINITIONS.append(('law of large numbers', 'AS INDEPENDENT TRIALS WITH THE SAME p INCREASE, RELATIVE FREQUENCY TENDS TOWARD TRUE PROBABILITY. SEE RELATIVE FREQUENCY AND EMPIRICAL PROBABILITY.'))

def definitions_menu():
    while True:
        key = STCORE.menu('DEFINITIONS', [
            ('1', 'SAMPLING TYPES / BIAS'),
            ('2', 'LEVELS OF MEASUREMENT'),
            ('3', 'ERRORS / SIGNIFICANCE'),
            ('4', 'OUTLIER'), ('5', 'SEARCH ALL DEFINITIONS'), ('6', 'SURVEY BIAS / QUOTAS')])
        if key == '0': return
        if key == '1': definition_list('SAMPLING TYPES / BIAS', SAMPLING_DEFINITIONS)
        elif key == '2': definition_list('MEASUREMENT LEVELS', MEASUREMENT_DEFINITIONS)
        elif key == '3': definition_list('ERRORS / SIGNIFICANCE', STUDY_DEFINITIONS[:4])
        elif key == '4': definition_pages(*STUDY_DEFINITIONS[-1])
        elif key == '6': definition_list('BIAS / QUOTAS', BIAS_DEFINITIONS)
        elif key == '5':
            term = input('SEARCH TERM: ').strip().lower()
            term = term.replace('convienience', 'convenience').replace('nonsampling', 'non-sampling')
            if not term: continue
            matches = []
            for group in (SAMPLING_DEFINITIONS, MEASUREMENT_DEFINITIONS,
                          STUDY_DEFINITIONS, BIAS_DEFINITIONS, DEFINITIONS):
                for name, definition in group:
                    if group is DEFINITIONS and name == 'outlier': continue
                    if term in name or term in definition.lower():
                        matches.append((name, definition))
            if matches: definition_list('SEARCH RESULTS', matches)
            else: definition_pages('NO MATCH', 'TRY SAMPLE, BIAS, ORDINAL, ERROR, SIGNIFICANT, OR OUTLIER.')

def study_menu():
    while True:
        key=STCORE.menu('STUDY / DEFINITIONS',[('1','SAMPLE / POPULATION'),('2','PARAMETER / STATISTIC'),('3','SAMPLING METHOD'),('4','OBSERVATIONAL / EXPERIMENT'),('5','DATA TYPE / MEASUREMENT'),('6','SIGNIFICANCE / ERROR'),('7','DEFINITIONS SEARCH'),('8','LAW OF LARGE NUMBERS'),('9','QUIZ 2 / SURVEY BIAS'),('10','QUIZ 3 / GRAPH GUIDE'),('11','QUIZ 4 / PROBABILITY'),('12','QUIZ 5 / DISTRIBUTIONS'),('13','PRACTICE TEST 1 / Q1-30')])
        if key=='0': return
        if key=='13':
            STCORE.call('STPRE','pretest_menu')
            continue
        if key=='12':
            STCORE.call('STQUIZ5','quiz_menu')
            continue
        if key=='11':
            STCORE.call('STQUIZ4','quiz_menu')
            continue
        if key=='10':
            STCORE.call('STQUIZ3','quiz_menu')
            continue
        if key=='9':
            STCORE.call('STQUIZ','quiz_menu')
            continue
        {'1':population_classifier,'2':parameter_classifier,'3':sampling_menu,'4':experiment_classifier,'5':measurement_menu,'6':significance_menu,'7':definitions_menu,'8':large_numbers}[key]()

def population_classifier():
    definition_pages('STUDY > POPULATION / SAMPLE','POPULATION: ENTIRE GROUP THE STUDY WANTS TO DESCRIBE. SAMPLE: SUBSET ACTUALLY OBSERVED. IDENTIFY THE TARGET GROUP FROM THE QUESTION; DO NOT ASSUME AN UNSTATED POPULATION.')
    key=STCORE.menu('STUDY > GROUP DESCRIBED',[('1','ENTIRE TARGET GROUP'),('2','SUBSET ACTUALLY OBSERVED'),('3','TARGET NOT STATED')])
    if key!='0': definition_pages('STUDY > ANSWER',{'1':'POPULATION','2':'SAMPLE','3':'NEED THE GROUP THE STUDY WANTS TO DESCRIBE BEFORE IDENTIFYING THE POPULATION.'}[key])

def parameter_classifier():
    entire=STCORE.yesno('BASED ON ENTIRE POPULATION?')
    definition_pages('STUDY > '+('PARAMETER' if entire else 'STATISTIC'),'PARAMETER DESCRIBES POPULATION. STATISTIC DESCRIBES SAMPLE. THIS APPLIES TO MEANS, SDs, COUNTS AND PERCENTAGES. PERCENTAGE ALONE DOES NOT DECIDE.')

def sampling_menu():
    key=STCORE.menu('STUDY > SAMPLING',[('1','IDENTIFY FROM DESCRIPTION'),('2','VIEW METHODS')])
    if key=='2': definition_list('STUDY > METHODS',SAMPLING_DEFINITIONS)
    elif key=='1':
        prompts=[('EASIEST PEOPLE TO REACH?',3),('RANDOM START, THEN EVERY kth?',2),('RANDOM SAMPLE FROM EVERY GROUP?',4),('RANDOMLY SELECT WHOLE GROUPS?',5),('ALL SIZE-n SUBSETS EQUALLY LIKELY?',0),('EVERY INDIVIDUAL EQUALLY LIKELY?',1)]
        for prompt,index in prompts:
            if STCORE.yesno(prompt):
                definition_pages(*SAMPLING_DEFINITIONS[index])
                return
        definition_pages('STUDY > NEED DETAILS','NEED THE SELECTION METHOD: HOW PEOPLE OR GROUPS WERE CHOSEN. DO NOT ASSUME RANDOM SELECTION.')

def experiment_classifier():
    yes=STCORE.yesno('RESEARCHERS IMPOSE A TREATMENT?')
    definition_pages('STUDY > '+('EXPERIMENT' if yes else 'OBSERVATIONAL'),'ASSIGNED OR IMPOSED TREATMENT MEANS EXPERIMENT. MERELY OBSERVING, MEASURING OR SURVEYING IS AN OBSERVATIONAL STUDY.')

def measurement_menu():
    key=STCORE.menu('STUDY > DATA TYPE',[('1','QUALITATIVE / QUANTITATIVE'),('2','DISCRETE / CONTINUOUS'),('3','MEASUREMENT LEVELS')])
    if key=='1': definition_pages('STUDY > DATA TYPE','QUALITATIVE: CATEGORIES OR LABELS. QUANTITATIVE: NUMERICAL COUNTS OR MEASUREMENTS. A NUMBER USED ONLY AS AN ID IS A LABEL.')
    elif key=='2': definition_pages('STUDY > DATA TYPE','DISCRETE: COUNTABLE VALUES, LIKE NUMBER OF CHILDREN. CONTINUOUS: MEASUREMENTS THROUGH AN INTERVAL, LIKE HEIGHT.')
    elif key=='3': definition_list('STUDY > MEASUREMENT',MEASUREMENT_DEFINITIONS)

def significance_menu():
    key=STCORE.menu('STUDY > SIGNIFICANCE',[('1','STATISTICAL VS PRACTICAL'),('2','ERROR DEFINITIONS'),('3','COMPARE p-VALUE / alpha')])
    if key=='1': definition_pages('STUDY > INTERPRETATION','STATISTICAL: UNLIKELY UNDER THE NULL; COMPARE p-VALUE TO alpha. PRACTICAL: IS THE EFFECT LARGE ENOUGH TO MATTER IN CONTEXT? CONSIDER EFFECT SIZE, COSTS AND CONSEQUENCES. STATISTICAL SIGNIFICANCE ALONE CANNOT DECIDE PRACTICAL IMPORTANCE.')
    elif key=='2': definition_list('STUDY > ERROR',STUDY_DEFINITIONS[:2])
    elif key=='3':
        p=STCORE.read_exact('p-VALUE: '); alpha=STCORE.read_exact('alpha: ')
        STCORE.results('STUDY > SIGNIFICANCE',[('STATISTICALLY SIGNIFICANT','YES' if STCORE.compare_exact(p,alpha)<=0 else 'NO'),('PRACTICALLY SIGNIFICANT','NEED EFFECT SIZE / CONTEXT')],['COMPARE p-VALUE <= alpha'])

def large_numbers():
    definition_pages('LAW OF LARGE NUMBERS','AS THE NUMBER OF INDEPENDENT TRIALS WITH THE SAME PROBABILITY BECOMES LARGE, RELATIVE FREQUENCY TENDS TO GET CLOSER TO THE TRUE PROBABILITY. SEE RELATIVE FREQUENCY AND EMPIRICAL PROBABILITY. THIS DOES NOT MEAN A LOSING STREAK MAKES A WIN DUE.')


def open_reference(name, context, *args):
    for key,value in context.items():
        if key not in globals(): globals()[key]=value
    return globals()[name](*args)
